language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash ./.travis-docker.sh
env:
 global:
   - PACKAGE="dns-forward"
 matrix:
   - DISTRO=alpine-3.4 OCAML_VERSION=4.03.0
