language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
 global:
   - PINS="dns-forward.dev:. dns-forward-lwt-unix.dev:."
 matrix:
   - OCAML_VERSION=4.03 PACKAGE="dns-forward"
   - OCAML_VERSION=4.04 PACKAGE="dns-forward-lwt-unix"
